DongtaiGoOpenapi: "https://iast-test.huoxian.cn/openapi"
DongtaiGoToken: "1f6b147d1790d2226e49ae6b822d83f2f911b55b"
DongtaiGoProjectName: "GO Project"
DongtaiGoProjectVersion: "0.1.0"
DongtaiGoProjectCreate: true